/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Shoferi;
import DAL.AutomjetiRepository;
import DAL.ShoferiException;
import DAL.ShoferiRepository;
import Model.AutomjetiComboBoxModel;
import Model.ShoferiTableModel;
import RegEx.NumriTelefonitValidator;
import com.sun.glass.events.KeyEvent;
import static java.lang.Character.isAlphabetic;
import static java.lang.Character.isDigit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author Lumi
 */
public class ShoferiForm extends javax.swing.JInternalFrame {

    ShoferiRepository shoferiRepository = new ShoferiRepository();
    ShoferiTableModel shoferiTableModel = new ShoferiTableModel();
    
    AutomjetiRepository automjetiRepository = new AutomjetiRepository();
    AutomjetiComboBoxModel automjetiComboBoxModel;
    /**
     * Creates new form ShoferiForm
     */
    public ShoferiForm() {
        initComponents();
        tabelaLoad();
        
    }
    public void emptyObject() {
        jTable1.clearSelection();
        txtNrPatentes.setText("");
        txtEmri.setText("");
        txtMbiemri.setText("");
        txtNrTelefonit.setText("");
    }
    
    private void tabelaLoad(){
        List<Shoferi> lista = shoferiRepository.findAll();
        shoferiTableModel.add(lista);
        jTable1.setModel(shoferiTableModel);
        shoferiTableModel.fireTableDataChanged();
        tabelaSelectedIndexChange();
    }
    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = jTable1.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    Shoferi shoferi = shoferiTableModel.getShoferi(selectedIndex);

                    txtNrPatentes.setText(shoferi.getNrPatentes());
                    txtEmri.setText(shoferi.getEmri());
                    txtMbiemri.setText(shoferi.getMbiemri());
                    txtNrTelefonit.setText(shoferi.getNrTelefonit());
                    
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmri = new javax.swing.JTextField();
        txtMbiemri = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNrTelefonit = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNrPatentes = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        telefoniGabim = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);

        jLabel1.setText("Nr. i Patentes:");

        jLabel2.setText("Emri:");

        jLabel3.setText("Mbiemri:");

        txtEmri.setPreferredSize(new java.awt.Dimension(6, 30));
        txtEmri.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmriFocusGained(evt);
            }
        });
        txtEmri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmriKeyTyped(evt);
            }
        });

        txtMbiemri.setPreferredSize(new java.awt.Dimension(6, 30));
        txtMbiemri.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMbiemriFocusGained(evt);
            }
        });
        txtMbiemri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMbiemriActionPerformed(evt);
            }
        });
        txtMbiemri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMbiemriKeyTyped(evt);
            }
        });

        jLabel4.setText("Nr. i Telefonit:");

        txtNrTelefonit.setPreferredSize(new java.awt.Dimension(6, 30));
        txtNrTelefonit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNrTelefonitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNrTelefonitFocusLost(evt);
            }
        });
        txtNrTelefonit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNrTelefonitActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1495665232_floppy.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setPreferredSize(new java.awt.Dimension(70, 30));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1495728739_update.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setPreferredSize(new java.awt.Dimension(70, 30));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(500, 64));
        jScrollPane1.setViewportView(jTable1);

        txtNrPatentes.setPreferredSize(new java.awt.Dimension(6, 30));
        txtNrPatentes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNrPatentesFocusGained(evt);
            }
        });
        txtNrPatentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNrPatentesActionPerformed(evt);
            }
        });
        txtNrPatentes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNrPatentesKeyTyped(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1495666218_delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(70, 30));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        telefoniGabim.setForeground(new java.awt.Color(255, 51, 0));
        telefoniGabim.setText("Numri i telefonit është gabim !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNrPatentes, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNrTelefonit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefoniGabim))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmri, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtMbiemri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNrPatentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(txtMbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNrTelefonit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(telefoniGabim)))
                .addGap(88, 88, 88)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            NumriTelefonitValidator v = new NumriTelefonitValidator();
            int row = jTable1.getSelectedRow();
            if (txtNrPatentes.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Ju lutem Shkruani Nr. e Patentes :", "Error", JOptionPane.ERROR_MESSAGE);
               
            } else if (txtEmri.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ju lutem Shkruani Emrin :", "Error", JOptionPane.ERROR_MESSAGE);
            }            
            else if (txtMbiemri.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ju lutem Shkruani Mbiemrin :", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if (!v.validate(txtNrTelefonit.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Ju lutem Shkruani Numrin e Telefonit :", "Error", JOptionPane.ERROR_MESSAGE);
            }else {
                if (row == -1) {
                    Shoferi shoferi = new Shoferi();
                    shoferi.setNrPatentes(txtNrPatentes.getText());
                    shoferi.setEmri(txtEmri.getText());
                    shoferi.setMbiemri(txtMbiemri.getText());
                    shoferi.setNrTelefonit(txtNrTelefonit.getText());
                    shoferiRepository.create(shoferi);
                    JOptionPane.showMessageDialog(this, "E dhëna u ruajt me sukses !");
                } else {
                    Shoferi shoferi = this.shoferiTableModel.getShoferi(row);

                    shoferi.setNrPatentes(txtNrPatentes.getText());
                    shoferi.setEmri(txtEmri.getText());
                    shoferi.setMbiemri(txtMbiemri.getText());
                    shoferi.setNrTelefonit(txtNrTelefonit.getText());
                    shoferiRepository.edit(shoferi);
                    JOptionPane.showMessageDialog(this, "E dhëna u editua me sukses");
                }
                emptyObject();
                tabelaLoad();
            }

        } catch (ShoferiException pe) {
            JOptionPane.showMessageDialog(this, pe.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        emptyObject();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            int row = jTable1.getSelectedRow();
            if(row > -1){
                Object [] ob = {"Po","Jo"};
                int i = javax.swing.JOptionPane.showOptionDialog(this, "A dëshironi ta fshini ?", "Fshirja", JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                if(i==0){
                    Shoferi shoferi = this.shoferiTableModel.getShoferi(row);
                    shoferiRepository.remove(shoferi);
                    tabelaLoad();
                    emptyObject();
//                    JOptionPane.showMessageDialog(this, "E dhëna është fshir me sukses !");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Nuk keni selektuar asgjë për të fshir !");
            }
        }catch(ShoferiException pe){
            JOptionPane.showMessageDialog(this, pe.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtMbiemriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMbiemriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMbiemriActionPerformed

    private void txtNrPatentesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNrPatentesKeyTyped
        char c = evt.getKeyChar();
        if(!(isDigit(c) || c == KeyEvent.VK_BACKSPACE)){
        evt.consume();
        }
    }//GEN-LAST:event_txtNrPatentesKeyTyped

    private void txtEmriKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmriKeyTyped
        char c = evt.getKeyChar();
        if(!(isAlphabetic(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_SHIFT)){
        evt.consume();
        }
    }//GEN-LAST:event_txtEmriKeyTyped

    private void txtMbiemriKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMbiemriKeyTyped
        char c = evt.getKeyChar();
        if(!(isAlphabetic(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_SHIFT)){
        evt.consume();
        }
    }//GEN-LAST:event_txtMbiemriKeyTyped

    private void txtNrTelefonitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNrTelefonitFocusLost
        NumriTelefonitValidator v = new NumriTelefonitValidator();
        if(!v.validate(txtNrTelefonit.getText().trim())){
            telefoniGabim.setVisible(true);
        }
    }//GEN-LAST:event_txtNrTelefonitFocusLost

    private void txtNrTelefonitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNrTelefonitFocusGained
        telefoniGabim.setVisible(false);
    }//GEN-LAST:event_txtNrTelefonitFocusGained

    private void txtNrPatentesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNrPatentesFocusGained
        telefoniGabim.setVisible(false);
    }//GEN-LAST:event_txtNrPatentesFocusGained

    private void txtEmriFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmriFocusGained
        telefoniGabim.setVisible(false);
    }//GEN-LAST:event_txtEmriFocusGained

    private void txtMbiemriFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMbiemriFocusGained
        telefoniGabim.setVisible(false);
    }//GEN-LAST:event_txtMbiemriFocusGained

    private void txtNrTelefonitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNrTelefonitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNrTelefonitActionPerformed

    private void txtNrPatentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNrPatentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNrPatentesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel telefoniGabim;
    private javax.swing.JTextField txtEmri;
    private javax.swing.JTextField txtMbiemri;
    private javax.swing.JTextField txtNrPatentes;
    private javax.swing.JTextField txtNrTelefonit;
    // End of variables declaration//GEN-END:variables
}